### ISSUE TITLE
[QUESTION/FEEDBACK] "rbac" attribute should be named something more generic, like "permissions"

### ISSUE THREAD

**Issue by anderseknert** [Parsifal-M/backstage-opa-plugins#142]
As OPA could leverage any combination of ACL's, RBAC, ABAC, ReBAC or what have you, it seems unnecessary to limit the name of the permissions plugin in the `opaClient` config to `rbac`. I'd suggest using `permissions` instead.

**Comment by Parsifal-M** [comment]
Renamed from `rbac` to `permissions`
