### ISSUE TITLE
[FEAT] Allow setting `entrypoint` in `opaClient` rather than `package`

### ISSUE THREAD

**Issue by anderseknert** [Parsifal-M/backstage-opa-plugins#143]
It wasn't clear from the docs what the name of the rule which was to be evaluated should be, as only the `package` was requested in configuration. The name shouldn't matter however, and I think it would be preferable if the user could set an `entrypoint` instead of a package. Entrypoints would be either a package or a package/rule combination and using any level of nesting, like `policy`, `policy/backstage/permissions` or `policy/backstage/permissions/decision`.

**Comment by Parsifal-M** [comment]
Just adding some notes here so that I do not forget :sweat_smile: 

- Move away from `response.decision.result` so that users can set their own `entrypoint` (decision)

This would mean they do not need to evaluate the whole policy.
