### ISSUE TITLE
[FEAT] Investigate alternative authorization model

### ISSUE THREAD

**Issue by anderseknert** [Parsifal-M/backstage-opa-plugins#148]
While the policy model provided by the Backstage permissions framework works great, it would also be interesting to explore models where OPA has more say in the decisions being made. More specifically, I'd like to see an implementation where OPA doesn't merely pass conditional queries back to the plugins, but overrides the decision-making entirely, and side-steps the plugin's ownership of permissions in favor of the decoupled, externalized model that's more commonly seen in OPA integrations. Both approaches have their pros and cons, of course, and we'll want to document how these differ as part of this. 

We got some helpful suggestions on how to accomplish this in the Backstage Discord (thanks @vinzscam!), like overriding the `PermissionEvaluator` interface with our own client implementation, so let's start there.

**Comment by Parsifal-M** [comment]
Closing this I think as for now, with the new "beta" plugins this is more or less solved, or at least for now, its as close as it can be!

Maybe later we can re-evaluate if we even need the wrapper anymore once we can play around a bit more with the `httpHandler` in Backstage.

But for now, we have both the community, core and custom plugins all setup to be able to use OPA for Authorisation! 🎉  I think eventually, people will see the awesome flexibility we have here and hopefully enjoy working on this as much as I do!
