### ISSUE TITLE
OPA wrapper module with RBAC plugin

### ISSUE THREAD

**Issue by MarkPorohnja** [Parsifal-M/backstage-opa-plugins#187]
## Quick Question/Feedback

**Question or Feedback:**
Hello. Just want to clarify. I am using RBAC plugin made by janus-idp. When I try to add OPA wrapper, Backstage fails. I want to use OPA wrapper to be able to create additional policies/permissions which I want to use with RBAC. Is it expected that app fails? In your docs, it is stated: "This plugin also requires and assumes that you have at least setup the permission framework (without any policies)".

**Plugin Name:**
@parsifal-m/plugin-permission-backend-module-opa-wrapper
@janus-idp/backstage-plugin-rbac-backend

**Additional Details:**
janus-idp RBAC plugin docs: https://github.com/janus-idp/backstage-plugins/blob/main/plugins/rbac-backend/README.md

![image](https://github.com/Parsifal-M/backstage-opa-plugins/assets/43471024/669434f9-40d1-4407-a2d2-ab2dfa6a2e47)

**Comment by Parsifal-M** [comment]
> ## Quick Question/Feedback
> **Question or Feedback:** Hello. Just want to clarify. I am using RBAC plugin made by janus-idp. When I try to add OPA wrapper, Backstage fails. I want to use OPA wrapper to be able to create additional policies/permissions which I want to use with RBAC. Is it expected that app fails? In your docs, it is stated: "This plugin also requires and assumes that you have at least setup the permission framework (without any policies)".

Hey! :wave: 

Thanks for stopping by! I had a quick look at the janus-idp RBAC plugin and I think the reason this is happening (based on what I understand from their docs) is that, for lack of better words the two plugins are "clashing" and both are fighting to leverage the permissions framework :sweat_smile: 

So sadly I think you won't be able to use both together :cry: 

The way this plugin works at a high level is that the permissions framework will just by default, forward all policy decisions to OPA.

Hope this helps? If you do want to give the plugin a try, feel free to reach out to me on here or discord (same username) :smiley:

**Comment by MarkPorohnja** [comment]
Thanks for your clarification. Sadly indeed.
